#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red (3).csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [5]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [6]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
y_train

array([5, 5, 5, ..., 6, 5, 6])

In [11]:
y_test

array([7, 6, 6, 7, 5, 7, 6, 6, 7, 7, 6, 6, 6, 5, 5, 5, 7, 7, 5, 6, 5, 6,
       5, 5, 4, 6, 7, 5, 4, 6, 6, 4, 7, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 7,
       6, 6, 6, 5, 6, 6, 7, 6, 7, 6, 6, 5, 5, 7, 5, 7, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 7, 6, 7, 6, 7, 5, 6, 5, 7, 6, 6, 5, 7, 5, 6, 7, 7, 5,
       5, 5, 6, 6, 5, 3, 7, 5, 4, 6, 7, 6, 5, 6, 5, 7, 6, 5, 5, 5, 5, 6,
       6, 5, 5, 5, 6, 5, 7, 7, 6, 7, 6, 5, 5, 5, 5, 6, 5, 6, 7, 6, 5, 6,
       6, 6, 5, 6, 5, 6, 6, 5, 6, 4, 6, 5, 5, 6, 5, 6, 7, 6, 5, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 5, 7, 5, 4, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5,
       5, 5, 6, 6, 6, 5, 7, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5, 7, 6, 4,
       7, 6, 5, 7, 7, 6, 7, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 7, 5, 5, 5, 7,
       5, 6, 7, 7, 6, 6, 6, 6, 5, 5, 6, 7, 6, 4, 5, 5, 6, 5, 5, 5, 5, 6,
       6, 7, 7, 5, 7, 6, 6, 6, 6, 4, 4, 6, 4, 5, 6, 5, 5, 5, 5, 6, 6, 5,
       7, 6, 5, 5, 5, 6, 8, 6, 5, 5, 6, 7, 5, 5, 6, 7, 5, 5, 6, 5, 5, 6,
       5, 6, 5, 7, 6, 5, 5, 6, 6, 5, 6, 5, 7, 5, 8,

In [12]:
x_train

array([[ 7.7  ,  0.965,  0.1  , ...,  3.26 ,  0.5  ,  9.5  ],
       [ 7.2  ,  0.66 ,  0.03 , ...,  3.53 ,  0.57 ,  9.7  ],
       [ 6.1  ,  0.6  ,  0.08 , ...,  3.38 ,  0.54 , 11.   ],
       ...,
       [ 7.7  ,  0.43 ,  0.25 , ...,  3.37 ,  0.58 , 10.5  ],
       [ 7.2  ,  0.62 ,  0.06 , ...,  3.51 ,  0.53 ,  9.7  ],
       [ 7.6  ,  0.43 ,  0.4  , ...,  3.44 ,  0.54 , 12.2  ]])

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [15]:
ntrain

array([[5],
       [5],
       [5],
       ...,
       [6],
       [5],
       [6]])

In [16]:

ntest

array([[7],
       [6],
       [6],
       [7],
       [5],
       [7],
       [6],
       [6],
       [7],
       [7],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [7],
       [7],
       [5],
       [6],
       [5],
       [6],
       [5],
       [5],
       [4],
       [6],
       [7],
       [5],
       [4],
       [6],
       [6],
       [4],
       [7],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [7],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [7],
       [6],
       [7],
       [6],
       [6],
       [5],
       [5],
       [7],
       [5],
       [7],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [7],
       [6],
       [7],
       [6],
       [7],
       [5],
       [6],
       [5],
       [7],
       [6],
       [6],
       [5],
       [7],
    

In [17]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [18]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [19]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [20]:
xn_train

array([[-0.3746431 ,  2.47071144, -0.87747867, ..., -0.32462524,
        -0.92353358, -0.85302205],
       [-0.66515391,  0.7396492 , -1.23708989, ...,  1.46102041,
        -0.5204528 , -0.66078114],
       [-1.30427768,  0.39911236, -0.98022474, ...,  0.46899505,
        -0.69320171,  0.58878474],
       ...,
       [-0.3746431 , -0.565742  , -0.10688322, ...,  0.40286002,
        -0.46286983,  0.10818248],
       [-0.66515391,  0.51262464, -1.0829708 , ...,  1.32875036,
        -0.75078468, -0.66078114],
       [-0.43274526, -0.565742  ,  0.66371224, ...,  0.86580519,
        -0.69320171,  1.74223018]])

In [21]:
xn_test

array([[ 0.26448068, -1.24681567,  0.66371224, ...,  0.00604988,
         0.74637253,  1.35774837],
       [-0.3746431 ,  0.28560009, -0.87747867, ..., -1.51505567,
        -0.98111655, -0.56466069],
       [-1.07186904,  2.10179654, -1.39120898, ...,  1.26261534,
        -0.17495498,  0.49266429],
       ...,
       [-1.01376688, -0.16844903, -1.39120898, ...,  0.86580519,
        -0.63561874,  1.83835063],
       [-1.82719713, -1.07654725, -1.39120898, ...,  2.45304577,
         0.74637253,  3.47239833],
       [-0.08413229, -0.11169289, -0.15825625, ...,  0.20445495,
        -0.11737201, -0.85302205]])

In [22]:
yn_train

array([[-0.7678401 ],
       [-0.7678401 ],
       [-0.7678401 ],
       ...,
       [ 0.48320128],
       [-0.7678401 ],
       [ 0.48320128]])

In [23]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [24]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [25]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [26]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [27]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [29]:

from sklearn.metrics import r2_score

In [30]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [31]:
print(r, l, d, s, p)

0.5024165915238954 0.3550059590236516 0.1253381424706944 0.3876465519411285 0.3550059590236516
